// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnb745Eww0mInGaWL1Ul4tcd0XIz5m-A',
    appId: '1:551743481101:web:0c6a7dc31eb034a8087c44',
    messagingSenderId: '551743481101',
    projectId: 'kebabybrno',
    authDomain: 'kebabybrno.firebaseapp.com',
    storageBucket: 'kebabybrno.firebasestorage.app',
    measurementId: 'G-206JK4FYLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzJyaozjXNFW0b86XadQmQI2g2T0t9dfc',
    appId: '1:551743481101:android:761563e777183c4f087c44',
    messagingSenderId: '551743481101',
    projectId: 'kebabybrno',
    storageBucket: 'kebabybrno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Ue-mozgng5Ja-A6w8MS01r-YAa8lQ3o',
    appId: '1:551743481101:ios:b39ee437a52ba8aa087c44',
    messagingSenderId: '551743481101',
    projectId: 'kebabybrno',
    storageBucket: 'kebabybrno.firebasestorage.app',
    iosBundleId: 'com.example.kebabyBrno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Ue-mozgng5Ja-A6w8MS01r-YAa8lQ3o',
    appId: '1:551743481101:ios:b39ee437a52ba8aa087c44',
    messagingSenderId: '551743481101',
    projectId: 'kebabybrno',
    storageBucket: 'kebabybrno.firebasestorage.app',
    iosBundleId: 'com.example.kebabyBrno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQnb745Eww0mInGaWL1Ul4tcd0XIz5m-A',
    appId: '1:551743481101:web:526121fbc07d9fcf087c44',
    messagingSenderId: '551743481101',
    projectId: 'kebabybrno',
    authDomain: 'kebabybrno.firebaseapp.com',
    storageBucket: 'kebabybrno.firebasestorage.app',
    measurementId: 'G-W3B6XWE0MH',
  );

}